---
- name: restart ntpd
  service: name=ntp state=restarted

- name: configure hostname
  service: name=hostname state=restarted

- name: set vim as the default editor
  command: update-alternatives --set editor /usr/bin/vim.nox
