---
- name: Upgrade packages
  tags: system
  apt: upgrade=dist update_cache=yes

- name: Install common packages and utilities
  apt: pkg=$item state=latest
  tags: system
  with_items:
    - iftop
    - htop
    - iotop
    - git-core
    - traceroute
    - dnsutils
    - whois
    - realpath
    - acl
    - telnet

- name: Install vim
  tags: system
  apt: pkg=vim-nox state=latest
  notify:
    - set vim as the default editor

- name: Cleanup packages
  tags: system
  command: apt-get autoremove -y

- name: Cleanup apt
  tags: system
  command: apt-get clean

- name: Update inputrc
  template: src=etc.inputrc.j2 dest=/etc/inputrc
  tags: system

- name: Install ntp
  tags: ntp
  apt: package=ntp state=installed

- name: Configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: Configure hostsfile
  template: src=etc.hosts.j2 dest=/etc/hosts
  notify:
    - configure hostname
  tags: hostname

- name: Configure hostname
  template: src=etc.hostname.j2 dest=/etc/hostname
  notify:
    - configure hostname
  tags: hostname

