---
# Install the required kernel for docker
- name: Install linux-image-{{ linux_kernel_version }}
  tags: docker,system
  apt: package=linux-image-{{ linux_kernel_version }} update_cache=yes

- name: Install linux-headers-{{ linux_kernel_version }}
  tags: docker,system
  apt: package=linux-headers-{{ linux_kernel_version }} update_cache=yes

- name: Enable extra cgroup controllers
  tags: docker,system
  template: src=etc.default.grub.j2 dest=/etc/default/grub
  notify:
    - update grub

# install docker
- name: Enable ppa adding via apt-add-repository is available
  tags: docker
  apt: pkg={{ item }} state=latest
  with_items: docker_deps

- name: Add docker ppa
  tags: docker
  apt_repository: repo=ppa:dotcloud/lxc-docker

- name: Install docker via ppa
  tags: docker
  apt: pkg=lxc-docker state=latest update_cache=yes
